//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.27 at 04:36:43 PM EDT 
//

package gov.nist.hit.iz.ws.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for connectivityTestRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="connectivityTestRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="echoBack" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "connectivityTestRequestType", propOrder = { "echoBack" })
@XmlRootElement(name = "connectivityTest")
public class ConnectivityTestRequestType {

	@XmlElement(required = true, nillable = true)
	protected String echoBack;

	/**
	 * Gets the value of the echoBack property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEchoBack() {
		return echoBack;
	}

	/**
	 * Sets the value of the echoBack property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEchoBack(String value) {
		this.echoBack = value;
	}

}
