//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.27 at 04:36:43 PM EDT 
//


package gov.nist.hit.iz.ws.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nist.healthcare.hl7.v2.iz.tool.ws.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConnectivityTest_QNAME = new QName("urn:cdc:iisb:2011", "connectivityTest");
    private final static QName _SubmitSingleMessageResponse_QNAME = new QName("urn:cdc:iisb:2011", "submitSingleMessageResponse");
    private final static QName _UnsupportedOperationFault_QNAME = new QName("urn:cdc:iisb:2011", "UnsupportedOperationFault");
    private final static QName _ConnectivityTestResponse_QNAME = new QName("urn:cdc:iisb:2011", "connectivityTestResponse");
    private final static QName _SubmitSingleMessage_QNAME = new QName("urn:cdc:iisb:2011", "submitSingleMessage");
    private final static QName _SecurityFault_QNAME = new QName("urn:cdc:iisb:2011", "SecurityFault");
    private final static QName _Fault_QNAME = new QName("urn:cdc:iisb:2011", "fault");
    private final static QName _MessageTooLargeFault_QNAME = new QName("urn:cdc:iisb:2011", "MessageTooLargeFault");
    private final static QName _SubmitSingleMessageRequestTypeFacilityID_QNAME = new QName("urn:cdc:iisb:2011", "facilityID");
    private final static QName _SubmitSingleMessageRequestTypeUsername_QNAME = new QName("urn:cdc:iisb:2011", "username");
    private final static QName _SubmitSingleMessageRequestTypePassword_QNAME = new QName("urn:cdc:iisb:2011", "password");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nist.healthcare.hl7.v2.iz.tool.ws.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubmitSingleMessageResponseType }
     * 
     */
    public SubmitSingleMessageResponseType createSubmitSingleMessageResponseType() {
        return new SubmitSingleMessageResponseType();
    }

    /**
     * Create an instance of {@link ConnectivityTestRequestType }
     * 
     */
    public ConnectivityTestRequestType createConnectivityTestRequestType() {
        return new ConnectivityTestRequestType();
    }

    /**
     * Create an instance of {@link UnsupportedOperationFaultType }
     * 
     */
    public UnsupportedOperationFaultType createUnsupportedOperationFaultType() {
        return new UnsupportedOperationFaultType();
    }

    /**
     * Create an instance of {@link SubmitSingleMessageRequestType }
     * 
     */
    public SubmitSingleMessageRequestType createSubmitSingleMessageRequestType() {
        return new SubmitSingleMessageRequestType();
    }

    /**
     * Create an instance of {@link ConnectivityTestResponseType }
     * 
     */
    public ConnectivityTestResponseType createConnectivityTestResponseType() {
        return new ConnectivityTestResponseType();
    }

    /**
     * Create an instance of {@link SecurityFaultType }
     * 
     */
    public SecurityFaultType createSecurityFaultType() {
        return new SecurityFaultType();
    }

    /**
     * Create an instance of {@link SoapFaultType }
     * 
     */
    public SoapFaultType createSoapFaultType() {
        return new SoapFaultType();
    }

    /**
     * Create an instance of {@link MessageTooLargeFaultType }
     * 
     */
    public MessageTooLargeFaultType createMessageTooLargeFaultType() {
        return new MessageTooLargeFaultType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectivityTestRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "connectivityTest")
    public JAXBElement<ConnectivityTestRequestType> createConnectivityTest(ConnectivityTestRequestType value) {
        return new JAXBElement<ConnectivityTestRequestType>(_ConnectivityTest_QNAME, ConnectivityTestRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmitSingleMessageResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "submitSingleMessageResponse")
    public JAXBElement<SubmitSingleMessageResponseType> createSubmitSingleMessageResponse(SubmitSingleMessageResponseType value) {
        return new JAXBElement<SubmitSingleMessageResponseType>(_SubmitSingleMessageResponse_QNAME, SubmitSingleMessageResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnsupportedOperationFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "UnsupportedOperationFault")
    public JAXBElement<UnsupportedOperationFaultType> createUnsupportedOperationFault(UnsupportedOperationFaultType value) {
        return new JAXBElement<UnsupportedOperationFaultType>(_UnsupportedOperationFault_QNAME, UnsupportedOperationFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectivityTestResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "connectivityTestResponse")
    public JAXBElement<ConnectivityTestResponseType> createConnectivityTestResponse(ConnectivityTestResponseType value) {
        return new JAXBElement<ConnectivityTestResponseType>(_ConnectivityTestResponse_QNAME, ConnectivityTestResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmitSingleMessageRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "submitSingleMessage")
    public JAXBElement<SubmitSingleMessageRequestType> createSubmitSingleMessage(SubmitSingleMessageRequestType value) {
        return new JAXBElement<SubmitSingleMessageRequestType>(_SubmitSingleMessage_QNAME, SubmitSingleMessageRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "SecurityFault")
    public JAXBElement<SecurityFaultType> createSecurityFault(SecurityFaultType value) {
        return new JAXBElement<SecurityFaultType>(_SecurityFault_QNAME, SecurityFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoapFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "fault")
    public JAXBElement<SoapFaultType> createFault(SoapFaultType value) {
        return new JAXBElement<SoapFaultType>(_Fault_QNAME, SoapFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageTooLargeFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "MessageTooLargeFault")
    public JAXBElement<MessageTooLargeFaultType> createMessageTooLargeFault(MessageTooLargeFaultType value) {
        return new JAXBElement<MessageTooLargeFaultType>(_MessageTooLargeFault_QNAME, MessageTooLargeFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "facilityID", scope = SubmitSingleMessageRequestType.class)
    public JAXBElement<String> createSubmitSingleMessageRequestTypeFacilityID(String value) {
        return new JAXBElement<String>(_SubmitSingleMessageRequestTypeFacilityID_QNAME, String.class, SubmitSingleMessageRequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "username", scope = SubmitSingleMessageRequestType.class)
    public JAXBElement<String> createSubmitSingleMessageRequestTypeUsername(String value) {
        return new JAXBElement<String>(_SubmitSingleMessageRequestTypeUsername_QNAME, String.class, SubmitSingleMessageRequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cdc:iisb:2011", name = "password", scope = SubmitSingleMessageRequestType.class)
    public JAXBElement<String> createSubmitSingleMessageRequestTypePassword(String value) {
        return new JAXBElement<String>(_SubmitSingleMessageRequestTypePassword_QNAME, String.class, SubmitSingleMessageRequestType.class, value);
    }

}
