//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.27 at 04:36:43 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:cdc:iisb:2011", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.nist.hit.iz.ws.jaxb;
