//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.27 at 04:36:43 PM EDT 
//

package gov.nist.hit.iz.ws.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for submitSingleMessageRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="submitSingleMessageRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="facilityID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hl7Message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "submitSingleMessageRequestType", propOrder = { "username",
		"password", "facilityID", "hl7Message" })
@XmlRootElement(name = "submitSingleMessage")
public class SubmitSingleMessageRequestType {

	@XmlElement(required = false, nillable = true)
	protected String username;

	@XmlElement(required = false, nillable = true)
	protected String password;

	@XmlElement(required = false, nillable = true)
	protected String facilityID;

	@XmlElement(required = true, nillable = true)
	protected String hl7Message;

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFacilityID() {
		return facilityID;
	}

	public void setFacilityID(String facilityID) {
		this.facilityID = facilityID;
	}

	/**
	 * Gets the value of the hl7Message property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHl7Message() {
		return hl7Message;
	}

	/**
	 * Sets the value of the hl7Message property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHl7Message(String value) {
		this.hl7Message = value;
	}

}
