package gov.nist.hit.iz.domain;

public enum IZTestType {
	GENERIC, SENDER_CONNECTIVITY, SENDER_MESSAGE_TOO_LARGE, SENDER_SECURITY_FAULT, SENDER_SUBMIT_SINGLE_MESSAGE, SENDER_UNKNOWN_FAULT, SENDER_UNSUPPORTED_OPERATION, RECEIVER_CONNECTIVITY, RECEIVER_MESSAGE_TOO_LARGE, RECEIVER_SECURITY_FAULT, RECEIVER_SUBMIT_SINGLE_MESSAGE, RECEIVER_UNKNOWN_FAULT, RECEIVER_UNSUPPORTED_OPERATION
}
