//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 09:15:28 PM EDT 
//


package gov.nist.hit.iz.domain.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssertionResultConstants.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssertionResultConstants">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AFFIRMATIVE"/>
 *     &lt;enumeration value="ERROR"/>
 *     &lt;enumeration value="WARNING"/>
 *     &lt;enumeration value="ALERT"/>
 *     &lt;enumeration value="IGNORE"/>
 *     &lt;enumeration value="NOTE"/>
 *     &lt;enumeration value="INFORMATIONAL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssertionResultConstants", namespace = "http://www.nist.gov/healthcare/validation")
@XmlEnum
public enum AssertionResultConstants {

    AFFIRMATIVE,
    ERROR,
    WARNING,
    ALERT,
    IGNORE,
    NOTE,
    INFORMATIONAL;

    public String value() {
        return name();
    }

    public static AssertionResultConstants fromValue(String v) {
        return valueOf(v);
    }

}
