//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 09:15:28 PM EDT 
//


package gov.nist.hit.iz.domain.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssertionTypeV3Constants.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssertionTypeV3Constants">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HUMAN_CHECK"/>
 *     &lt;enumeration value="DATA"/>
 *     &lt;enumeration value="DATA_PASSED"/>
 *     &lt;enumeration value="MESSAGE_VALIDATION_CONTEXT"/>
 *     &lt;enumeration value="STRUCTURE"/>
 *     &lt;enumeration value="SOAP"/>
 *     &lt;enumeration value="WSA"/>
 *     &lt;enumeration value="HTTP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssertionTypeV3Constants", namespace = "http://www.nist.gov/healthcare/validation")
@XmlEnum
public enum AssertionTypeV3Constants {

    HUMAN_CHECK,
    DATA,
    DATA_PASSED,
    MESSAGE_VALIDATION_CONTEXT,
    STRUCTURE,
    SOAP,
    WSA,
    HTTP;

    public String value() {
        return name();
    }

    public static AssertionTypeV3Constants fromValue(String v) {
        return valueOf(v);
    }

}
