//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 09:15:28 PM EDT 
//


package gov.nist.hit.iz.domain.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssertionTypeProfileConstants.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssertionTypeProfileConstants">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VERSION"/>
 *     &lt;enumeration value="MESSAGE_STRUCTURE_ID"/>
 *     &lt;enumeration value="PROFILE_TYPE"/>
 *     &lt;enumeration value="PROFILE_STRUCTURE"/>
 *     &lt;enumeration value="SEGMENT_NAME"/>
 *     &lt;enumeration value="USAGE"/>
 *     &lt;enumeration value="CARDINALITY"/>
 *     &lt;enumeration value="LENGTH"/>
 *     &lt;enumeration value="USAGE_CARDINALITY"/>
 *     &lt;enumeration value="STANDARD_DEVIATION"/>
 *     &lt;enumeration value="RULE_DEVIATION"/>
 *     &lt;enumeration value="PROFILE_VALIDATION_CONTEXT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssertionTypeProfileConstants", namespace = "http://www.nist.gov/healthcare/validation")
@XmlEnum
public enum AssertionTypeProfileConstants {

    VERSION,
    MESSAGE_STRUCTURE_ID,
    PROFILE_TYPE,
    PROFILE_STRUCTURE,
    SEGMENT_NAME,
    USAGE,
    CARDINALITY,
    LENGTH,
    USAGE_CARDINALITY,
    STANDARD_DEVIATION,
    RULE_DEVIATION,
    PROFILE_VALIDATION_CONTEXT;

    public String value() {
        return name();
    }

    public static AssertionTypeProfileConstants fromValue(String v) {
        return valueOf(v);
    }

}
