//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 09:14:57 PM EDT 
//


package gov.nist.hit.iz.domain.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HL7V3MessageReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HL7V3MessageReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetaData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Message">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Filename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Context" type="{http://www.nist.gov/healthcare/validation/message/hl7/v3/context}HL7V3MessageValidationContextDefinition"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AssertionList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="Assertion">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Location">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                                       &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                                       &lt;element name="XPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AssertionDeclaration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionTypeV3Constants" />
 *                           &lt;attribute name="Result" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionResultConstants" />
 *                           &lt;attribute name="Severity" use="required" type="{http://www.nist.gov/healthcare/validation}ErrorSeverityConstants" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HL7V3MessageReport", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report", propOrder = {
    "metaData",
    "assertionList"
})
public class HL7V3MessageReport {

    @XmlElement(name = "MetaData", required = true)
    protected HL7V3MessageReport.MetaData metaData;
    @XmlElement(name = "AssertionList")
    protected HL7V3MessageReport.AssertionList assertionList;

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link HL7V3MessageReport.MetaData }
     *     
     */
    public HL7V3MessageReport.MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL7V3MessageReport.MetaData }
     *     
     */
    public void setMetaData(HL7V3MessageReport.MetaData value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the assertionList property.
     * 
     * @return
     *     possible object is
     *     {@link HL7V3MessageReport.AssertionList }
     *     
     */
    public HL7V3MessageReport.AssertionList getAssertionList() {
        return assertionList;
    }

    /**
     * Sets the value of the assertionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL7V3MessageReport.AssertionList }
     *     
     */
    public void setAssertionList(HL7V3MessageReport.AssertionList value) {
        this.assertionList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="Assertion">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Location">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                             &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                             &lt;element name="XPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AssertionDeclaration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionTypeV3Constants" />
     *                 &lt;attribute name="Result" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionResultConstants" />
     *                 &lt;attribute name="Severity" use="required" type="{http://www.nist.gov/healthcare/validation}ErrorSeverityConstants" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "assertion"
    })
    public static class AssertionList {

        @XmlElement(name = "Assertion", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report", required = true)
        protected List<HL7V3MessageReport.AssertionList.Assertion> assertion;

        /**
         * Gets the value of the assertion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the assertion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssertion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HL7V3MessageReport.AssertionList.Assertion }
         * 
         * 
         */
        public List<HL7V3MessageReport.AssertionList.Assertion> getAssertion() {
            if (assertion == null) {
                assertion = new ArrayList<HL7V3MessageReport.AssertionList.Assertion>();
            }
            return this.assertion;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Location">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *                   &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *                   &lt;element name="XPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AssertionDeclaration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionTypeV3Constants" />
         *       &lt;attribute name="Result" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionResultConstants" />
         *       &lt;attribute name="Severity" use="required" type="{http://www.nist.gov/healthcare/validation}ErrorSeverityConstants" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "location",
            "content",
            "description",
            "assertionDeclaration",
            "reference"
        })
        public static class Assertion {

            @XmlElement(name = "Location", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report", required = true)
            protected HL7V3MessageReport.AssertionList.Assertion.Location location;
            @XmlElement(name = "Content", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report")
            protected String content;
            @XmlElement(name = "Description", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report", required = true)
            protected String description;
            @XmlElement(name = "AssertionDeclaration", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report")
            protected String assertionDeclaration;
            @XmlElement(name = "Reference", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report")
            protected String reference;
            @XmlAttribute(name = "Type", required = true)
            protected AssertionTypeV3Constants type;
            @XmlAttribute(name = "Result", required = true)
            protected AssertionResultConstants result;
            @XmlAttribute(name = "Severity", required = true)
            protected ErrorSeverityConstants severity;

            /**
             * Gets the value of the location property.
             * 
             * @return
             *     possible object is
             *     {@link HL7V3MessageReport.AssertionList.Assertion.Location }
             *     
             */
            public HL7V3MessageReport.AssertionList.Assertion.Location getLocation() {
                return location;
            }

            /**
             * Sets the value of the location property.
             * 
             * @param value
             *     allowed object is
             *     {@link HL7V3MessageReport.AssertionList.Assertion.Location }
             *     
             */
            public void setLocation(HL7V3MessageReport.AssertionList.Assertion.Location value) {
                this.location = value;
            }

            /**
             * Gets the value of the content property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContent() {
                return content;
            }

            /**
             * Sets the value of the content property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContent(String value) {
                this.content = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the assertionDeclaration property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAssertionDeclaration() {
                return assertionDeclaration;
            }

            /**
             * Sets the value of the assertionDeclaration property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAssertionDeclaration(String value) {
                this.assertionDeclaration = value;
            }

            /**
             * Gets the value of the reference property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReference() {
                return reference;
            }

            /**
             * Sets the value of the reference property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReference(String value) {
                this.reference = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link AssertionTypeV3Constants }
             *     
             */
            public AssertionTypeV3Constants getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link AssertionTypeV3Constants }
             *     
             */
            public void setType(AssertionTypeV3Constants value) {
                this.type = value;
            }

            /**
             * Gets the value of the result property.
             * 
             * @return
             *     possible object is
             *     {@link AssertionResultConstants }
             *     
             */
            public AssertionResultConstants getResult() {
                return result;
            }

            /**
             * Sets the value of the result property.
             * 
             * @param value
             *     allowed object is
             *     {@link AssertionResultConstants }
             *     
             */
            public void setResult(AssertionResultConstants value) {
                this.result = value;
            }

            /**
             * Gets the value of the severity property.
             * 
             * @return
             *     possible object is
             *     {@link ErrorSeverityConstants }
             *     
             */
            public ErrorSeverityConstants getSeverity() {
                return severity;
            }

            /**
             * Sets the value of the severity property.
             * 
             * @param value
             *     allowed object is
             *     {@link ErrorSeverityConstants }
             *     
             */
            public void setSeverity(ErrorSeverityConstants value) {
                this.severity = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
             *         &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
             *         &lt;element name="XPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "line",
                "column",
                "xPath"
            })
            public static class Location {

                @XmlElement(name = "Line", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report")
                protected Integer line;
                @XmlElement(name = "Column", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report")
                protected Integer column;
                @XmlElement(name = "XPath", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report")
                protected String xPath;

                /**
                 * Gets the value of the line property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getLine() {
                    return line;
                }

                /**
                 * Sets the value of the line property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setLine(Integer value) {
                    this.line = value;
                }

                /**
                 * Gets the value of the column property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getColumn() {
                    return column;
                }

                /**
                 * Sets the value of the column property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setColumn(Integer value) {
                    this.column = value;
                }

                /**
                 * Gets the value of the xPath property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getXPath() {
                    return xPath;
                }

                /**
                 * Sets the value of the xPath property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setXPath(String value) {
                    this.xPath = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Message">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Filename" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Context" type="{http://www.nist.gov/healthcare/validation/message/hl7/v3/context}HL7V3MessageValidationContextDefinition"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "message",
        "context"
    })
    public static class MetaData {

        @XmlElement(name = "Message", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report", required = true)
        protected HL7V3MessageReport.MetaData.Message message;
        @XmlElement(name = "Context", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report", required = true)
        protected HL7V3MessageValidationContextDefinition context;

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link HL7V3MessageReport.MetaData.Message }
         *     
         */
        public HL7V3MessageReport.MetaData.Message getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link HL7V3MessageReport.MetaData.Message }
         *     
         */
        public void setMessage(HL7V3MessageReport.MetaData.Message value) {
            this.message = value;
        }

        /**
         * Gets the value of the context property.
         * 
         * @return
         *     possible object is
         *     {@link HL7V3MessageValidationContextDefinition }
         *     
         */
        public HL7V3MessageValidationContextDefinition getContext() {
            return context;
        }

        /**
         * Sets the value of the context property.
         * 
         * @param value
         *     allowed object is
         *     {@link HL7V3MessageValidationContextDefinition }
         *     
         */
        public void setContext(HL7V3MessageValidationContextDefinition value) {
            this.context = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Filename" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Message {

            @XmlElement(name = "Content", namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v3/report")
            protected Object content;
            @XmlAttribute(name = "Id")
            protected String id;
            @XmlAttribute(name = "Filename")
            protected String filename;

            /**
             * Gets the value of the content property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getContent() {
                return content;
            }

            /**
             * Sets the value of the content property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setContent(Object value) {
                this.content = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the filename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilename() {
                return filename;
            }

            /**
             * Sets the value of the filename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilename(String value) {
                this.filename = value;
            }

        }

    }

}
