//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 09:15:39 PM EDT 
//


package gov.nist.hit.iz.domain.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ReportHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ValidationStatus" type="{http://www.nist.gov/healthcare/validation/message}ValidationStatusType"/>
 *         &lt;element name="ValidationStatusInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StandardType" type="{http://www.nist.gov/healthcare/validation/message}StandardTypeType"/>
 *         &lt;element name="StandardVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ValidationType" type="{http://www.nist.gov/healthcare/validation/message}ValidationType"/>
 *         &lt;element name="TestIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceTestIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResultsID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExtendedResultsID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateOfTest" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="TimeOfTest" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="ValidationObjectReferenceList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="ValidationObjectReference">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation/message}ValidationObjectReferenceType" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TestObjectReferenceList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="TestObjectReference">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation/message}TestObjectReferenceType" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PositiveAssertionIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ResultOfTest" type="{http://www.nist.gov/healthcare/validation/message}ResultOfTestType"/>
 *         &lt;element name="TotalAssertionsMade" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AffirmCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ErrorCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="WarningCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="IgnoreCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="NoteCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AlertCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="InformationalCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ReportIntegrityIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ReportIntegrityObject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TestObject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportHeader", propOrder = {
    "validationStatus",
    "validationStatusInfo",
    "serviceName",
    "serviceProvider",
    "serviceVersion",
    "standardType",
    "standardVersion",
    "validationType",
    "testIdentifier",
    "serviceTestIdentifier",
    "resultsID",
    "extendedResultsID",
    "dateOfTest",
    "timeOfTest",
    "validationObjectReferenceList",
    "testObjectReferenceList",
    "positiveAssertionIndicator",
    "resultOfTest",
    "totalAssertionsMade",
    "affirmCount",
    "errorCount",
    "warningCount",
    "ignoreCount",
    "noteCount",
    "alertCount",
    "informationalCount",
    "reportIntegrityIndicator",
    "reportIntegrityObject",
    "testObject"
})
public class ReportHeader {

    @XmlElement(name = "ValidationStatus", required = true)
    @XmlSchemaType(name = "string")
    protected ValidationStatusType validationStatus;
    @XmlElement(name = "ValidationStatusInfo")
    protected String validationStatusInfo;
    @XmlElement(name = "ServiceName", required = true)
    protected String serviceName;
    @XmlElement(name = "ServiceProvider", required = true)
    protected String serviceProvider;
    @XmlElement(name = "ServiceVersion")
    protected String serviceVersion;
    @XmlElement(name = "StandardType", required = true)
    @XmlSchemaType(name = "string")
    protected StandardTypeType standardType;
    @XmlElement(name = "StandardVersion", required = true)
    protected String standardVersion;
    @XmlElement(name = "ValidationType", required = true)
    @XmlSchemaType(name = "string")
    protected ValidationType validationType;
    @XmlElement(name = "TestIdentifier", required = true)
    protected String testIdentifier;
    @XmlElement(name = "ServiceTestIdentifier")
    protected String serviceTestIdentifier;
    @XmlElement(name = "ResultsID")
    protected String resultsID;
    @XmlElement(name = "ExtendedResultsID")
    protected String extendedResultsID;
    @XmlElement(name = "DateOfTest", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfTest;
    @XmlElement(name = "TimeOfTest", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar timeOfTest;
    @XmlElement(name = "ValidationObjectReferenceList", required = true)
    protected ReportHeader.ValidationObjectReferenceList validationObjectReferenceList;
    @XmlElement(name = "TestObjectReferenceList")
    protected ReportHeader.TestObjectReferenceList testObjectReferenceList;
    @XmlElement(name = "PositiveAssertionIndicator")
    protected boolean positiveAssertionIndicator;
    @XmlElement(name = "ResultOfTest", required = true)
    @XmlSchemaType(name = "string")
    protected ResultOfTestType resultOfTest;
    @XmlElement(name = "TotalAssertionsMade")
    protected Integer totalAssertionsMade;
    @XmlElement(name = "AffirmCount")
    protected Integer affirmCount;
    @XmlElement(name = "ErrorCount")
    protected int errorCount;
    @XmlElement(name = "WarningCount")
    protected Integer warningCount;
    @XmlElement(name = "IgnoreCount")
    protected Integer ignoreCount;
    @XmlElement(name = "NoteCount")
    protected Integer noteCount;
    @XmlElement(name = "AlertCount")
    protected Integer alertCount;
    @XmlElement(name = "InformationalCount")
    protected Integer informationalCount;
    @XmlElement(name = "ReportIntegrityIndicator")
    protected Boolean reportIntegrityIndicator;
    @XmlElement(name = "ReportIntegrityObject")
    protected String reportIntegrityObject;
    @XmlElement(name = "TestObject")
    protected String testObject;

    /**
     * Gets the value of the validationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationStatusType }
     *     
     */
    public ValidationStatusType getValidationStatus() {
        return validationStatus;
    }

    /**
     * Sets the value of the validationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationStatusType }
     *     
     */
    public void setValidationStatus(ValidationStatusType value) {
        this.validationStatus = value;
    }

    /**
     * Gets the value of the validationStatusInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationStatusInfo() {
        return validationStatusInfo;
    }

    /**
     * Sets the value of the validationStatusInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationStatusInfo(String value) {
        this.validationStatusInfo = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the serviceProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProvider() {
        return serviceProvider;
    }

    /**
     * Sets the value of the serviceProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProvider(String value) {
        this.serviceProvider = value;
    }

    /**
     * Gets the value of the serviceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceVersion() {
        return serviceVersion;
    }

    /**
     * Sets the value of the serviceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceVersion(String value) {
        this.serviceVersion = value;
    }

    /**
     * Gets the value of the standardType property.
     * 
     * @return
     *     possible object is
     *     {@link StandardTypeType }
     *     
     */
    public StandardTypeType getStandardType() {
        return standardType;
    }

    /**
     * Sets the value of the standardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardTypeType }
     *     
     */
    public void setStandardType(StandardTypeType value) {
        this.standardType = value;
    }

    /**
     * Gets the value of the standardVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardVersion() {
        return standardVersion;
    }

    /**
     * Sets the value of the standardVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardVersion(String value) {
        this.standardVersion = value;
    }

    /**
     * Gets the value of the validationType property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationType }
     *     
     */
    public ValidationType getValidationType() {
        return validationType;
    }

    /**
     * Sets the value of the validationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationType }
     *     
     */
    public void setValidationType(ValidationType value) {
        this.validationType = value;
    }

    /**
     * Gets the value of the testIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestIdentifier() {
        return testIdentifier;
    }

    /**
     * Sets the value of the testIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestIdentifier(String value) {
        this.testIdentifier = value;
    }

    /**
     * Gets the value of the serviceTestIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceTestIdentifier() {
        return serviceTestIdentifier;
    }

    /**
     * Sets the value of the serviceTestIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceTestIdentifier(String value) {
        this.serviceTestIdentifier = value;
    }

    /**
     * Gets the value of the resultsID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultsID() {
        return resultsID;
    }

    /**
     * Sets the value of the resultsID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultsID(String value) {
        this.resultsID = value;
    }

    /**
     * Gets the value of the extendedResultsID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendedResultsID() {
        return extendedResultsID;
    }

    /**
     * Sets the value of the extendedResultsID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendedResultsID(String value) {
        this.extendedResultsID = value;
    }

    /**
     * Gets the value of the dateOfTest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfTest() {
        return dateOfTest;
    }

    /**
     * Sets the value of the dateOfTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfTest(XMLGregorianCalendar value) {
        this.dateOfTest = value;
    }

    /**
     * Gets the value of the timeOfTest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeOfTest() {
        return timeOfTest;
    }

    /**
     * Sets the value of the timeOfTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeOfTest(XMLGregorianCalendar value) {
        this.timeOfTest = value;
    }

    /**
     * Gets the value of the validationObjectReferenceList property.
     * 
     * @return
     *     possible object is
     *     {@link ReportHeader.ValidationObjectReferenceList }
     *     
     */
    public ReportHeader.ValidationObjectReferenceList getValidationObjectReferenceList() {
        return validationObjectReferenceList;
    }

    /**
     * Sets the value of the validationObjectReferenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportHeader.ValidationObjectReferenceList }
     *     
     */
    public void setValidationObjectReferenceList(ReportHeader.ValidationObjectReferenceList value) {
        this.validationObjectReferenceList = value;
    }

    /**
     * Gets the value of the testObjectReferenceList property.
     * 
     * @return
     *     possible object is
     *     {@link ReportHeader.TestObjectReferenceList }
     *     
     */
    public ReportHeader.TestObjectReferenceList getTestObjectReferenceList() {
        return testObjectReferenceList;
    }

    /**
     * Sets the value of the testObjectReferenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportHeader.TestObjectReferenceList }
     *     
     */
    public void setTestObjectReferenceList(ReportHeader.TestObjectReferenceList value) {
        this.testObjectReferenceList = value;
    }

    /**
     * Gets the value of the positiveAssertionIndicator property.
     * 
     */
    public boolean isPositiveAssertionIndicator() {
        return positiveAssertionIndicator;
    }

    /**
     * Sets the value of the positiveAssertionIndicator property.
     * 
     */
    public void setPositiveAssertionIndicator(boolean value) {
        this.positiveAssertionIndicator = value;
    }

    /**
     * Gets the value of the resultOfTest property.
     * 
     * @return
     *     possible object is
     *     {@link ResultOfTestType }
     *     
     */
    public ResultOfTestType getResultOfTest() {
        return resultOfTest;
    }

    /**
     * Sets the value of the resultOfTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultOfTestType }
     *     
     */
    public void setResultOfTest(ResultOfTestType value) {
        this.resultOfTest = value;
    }

    /**
     * Gets the value of the totalAssertionsMade property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalAssertionsMade() {
        return totalAssertionsMade;
    }

    /**
     * Sets the value of the totalAssertionsMade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalAssertionsMade(Integer value) {
        this.totalAssertionsMade = value;
    }

    /**
     * Gets the value of the affirmCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAffirmCount() {
        return affirmCount;
    }

    /**
     * Sets the value of the affirmCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAffirmCount(Integer value) {
        this.affirmCount = value;
    }

    /**
     * Gets the value of the errorCount property.
     * 
     */
    public int getErrorCount() {
        return errorCount;
    }

    /**
     * Sets the value of the errorCount property.
     * 
     */
    public void setErrorCount(int value) {
        this.errorCount = value;
    }

    /**
     * Gets the value of the warningCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWarningCount() {
        return warningCount;
    }

    /**
     * Sets the value of the warningCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWarningCount(Integer value) {
        this.warningCount = value;
    }

    /**
     * Gets the value of the ignoreCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIgnoreCount() {
        return ignoreCount;
    }

    /**
     * Sets the value of the ignoreCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIgnoreCount(Integer value) {
        this.ignoreCount = value;
    }

    /**
     * Gets the value of the noteCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNoteCount() {
        return noteCount;
    }

    /**
     * Sets the value of the noteCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNoteCount(Integer value) {
        this.noteCount = value;
    }

    /**
     * Gets the value of the alertCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAlertCount() {
        return alertCount;
    }

    /**
     * Sets the value of the alertCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAlertCount(Integer value) {
        this.alertCount = value;
    }

    /**
     * Gets the value of the informationalCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInformationalCount() {
        return informationalCount;
    }

    /**
     * Sets the value of the informationalCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInformationalCount(Integer value) {
        this.informationalCount = value;
    }

    /**
     * Gets the value of the reportIntegrityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReportIntegrityIndicator() {
        return reportIntegrityIndicator;
    }

    /**
     * Sets the value of the reportIntegrityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReportIntegrityIndicator(Boolean value) {
        this.reportIntegrityIndicator = value;
    }

    /**
     * Gets the value of the reportIntegrityObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportIntegrityObject() {
        return reportIntegrityObject;
    }

    /**
     * Sets the value of the reportIntegrityObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportIntegrityObject(String value) {
        this.reportIntegrityObject = value;
    }

    /**
     * Gets the value of the testObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestObject() {
        return testObject;
    }

    /**
     * Sets the value of the testObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestObject(String value) {
        this.testObject = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="TestObjectReference">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation/message}TestObjectReferenceType" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "testObjectReference"
    })
    public static class TestObjectReferenceList {

        @XmlElement(name = "TestObjectReference")
        protected List<ReportHeader.TestObjectReferenceList.TestObjectReference> testObjectReference;

        /**
         * Gets the value of the testObjectReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the testObjectReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTestObjectReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReportHeader.TestObjectReferenceList.TestObjectReference }
         * 
         * 
         */
        public List<ReportHeader.TestObjectReferenceList.TestObjectReference> getTestObjectReference() {
            if (testObjectReference == null) {
                testObjectReference = new ArrayList<ReportHeader.TestObjectReferenceList.TestObjectReference>();
            }
            return this.testObjectReference;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation/message}TestObjectReferenceType" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class TestObjectReference {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Type", required = true)
            protected TestObjectReferenceType type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link TestObjectReferenceType }
             *     
             */
            public TestObjectReferenceType getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link TestObjectReferenceType }
             *     
             */
            public void setType(TestObjectReferenceType value) {
                this.type = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="ValidationObjectReference">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation/message}ValidationObjectReferenceType" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "validationObjectReference"
    })
    public static class ValidationObjectReferenceList {

        @XmlElement(name = "ValidationObjectReference", required = true)
        protected List<ReportHeader.ValidationObjectReferenceList.ValidationObjectReference> validationObjectReference;

        /**
         * Gets the value of the validationObjectReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the validationObjectReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValidationObjectReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReportHeader.ValidationObjectReferenceList.ValidationObjectReference }
         * 
         * 
         */
        public List<ReportHeader.ValidationObjectReferenceList.ValidationObjectReference> getValidationObjectReference() {
            if (validationObjectReference == null) {
                validationObjectReference = new ArrayList<ReportHeader.ValidationObjectReferenceList.ValidationObjectReference>();
            }
            return this.validationObjectReference;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation/message}ValidationObjectReferenceType" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class ValidationObjectReference {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Type", required = true)
            protected ValidationObjectReferenceType type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link ValidationObjectReferenceType }
             *     
             */
            public ValidationObjectReferenceType getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link ValidationObjectReferenceType }
             *     
             */
            public void setType(ValidationObjectReferenceType value) {
                this.type = value;
            }

        }

    }

}
