//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 09:15:28 PM EDT 
//


package gov.nist.hit.iz.domain.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for Value complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Value">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PlainText">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="ignoreCase" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                 &lt;attribute name="interpretAsNumber" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Empty" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Present" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Location" type="{http://www.nist.gov/healthcare/message}MessageElement"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Value", namespace = "http://www.nist.gov/healthcare/validation", propOrder = {
    "plainText",
    "regex",
    "empty",
    "present",
    "location"
})
public class Value {

    @XmlElement(name = "PlainText")
    protected Value.PlainText plainText;
    @XmlElement(name = "Regex")
    protected String regex;
    @XmlElement(name = "Empty")
    protected Object empty;
    @XmlElement(name = "Present")
    protected Object present;
    @XmlElement(name = "Location")
    protected MessageElement location;

    /**
     * Gets the value of the plainText property.
     * 
     * @return
     *     possible object is
     *     {@link Value.PlainText }
     *     
     */
    public Value.PlainText getPlainText() {
        return plainText;
    }

    /**
     * Sets the value of the plainText property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value.PlainText }
     *     
     */
    public void setPlainText(Value.PlainText value) {
        this.plainText = value;
    }

    /**
     * Gets the value of the regex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegex() {
        return regex;
    }

    /**
     * Sets the value of the regex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegex(String value) {
        this.regex = value;
    }

    /**
     * Gets the value of the empty property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEmpty() {
        return empty;
    }

    /**
     * Sets the value of the empty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEmpty(Object value) {
        this.empty = value;
    }

    /**
     * Gets the value of the present property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPresent() {
        return present;
    }

    /**
     * Sets the value of the present property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPresent(Object value) {
        this.present = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link MessageElement }
     *     
     */
    public MessageElement getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageElement }
     *     
     */
    public void setLocation(MessageElement value) {
        this.location = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="ignoreCase" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *       &lt;attribute name="interpretAsNumber" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PlainText {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "ignoreCase")
        protected Boolean ignoreCase;
        @XmlAttribute(name = "interpretAsNumber")
        protected Boolean interpretAsNumber;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the ignoreCase property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isIgnoreCase() {
            if (ignoreCase == null) {
                return true;
            } else {
                return ignoreCase;
            }
        }

        /**
         * Sets the value of the ignoreCase property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIgnoreCase(Boolean value) {
            this.ignoreCase = value;
        }

        /**
         * Gets the value of the interpretAsNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isInterpretAsNumber() {
            if (interpretAsNumber == null) {
                return false;
            } else {
                return interpretAsNumber;
            }
        }

        /**
         * Sets the value of the interpretAsNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setInterpretAsNumber(Boolean value) {
            this.interpretAsNumber = value;
        }

    }

}
